# Generated by Django 3.2.3 on 2021-05-17 17:38

import django.db.models.deletion
import localflavor.generic.models
from django.db import migrations, models

import reports.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("PLN", "PLN"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="In units of currency's denomination"
                    ),
                ),
                ("description", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.payment",
                    ),
                ),
                ("cardholder_name", models.CharField(max_length=256)),
                ("cardholder_surname", models.CharField(max_length=256)),
                (
                    "card_number",
                    models.CharField(
                        max_length=16, validators=[reports.validators.check_card]
                    ),
                ),
            ],
            bases=("reports.payment",),
        ),
        migrations.CreateModel(
            name="DirectPayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.payment",
                    ),
                ),
                (
                    "iban",
                    localflavor.generic.models.IBANField(
                        include_countries=None,
                        max_length=34,
                        use_nordea_extensions=False,
                    ),
                ),
            ],
            bases=("reports.payment",),
        ),
        migrations.CreateModel(
            name="PayByLink",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.payment",
                    ),
                ),
                ("bank", models.CharField(max_length=256)),
            ],
            bases=("reports.payment",),
        ),
    ]
